### ISSUE TITLE
Readme Issue

### ISSUE THREAD

**Issue by felipekm** [Tlantic/cdv-socket-plugin#30]
The 'Send' example on readme is differently if compared with the implementation in www/Socket.js:
send (successCallback, errorCallback, host, port, data)

Should be "send (successCallback, errorCallback, connectionId, data)" as is on socket.js line 31;

Also there's a silent bug as you can see on the other sample functions, the IP is such this: '192.168.2..5', with two dots after the number 2.

**Comment by vinnylinck** [comment]
Fixed on @28d192f94c66d9b589efbc9d0d7c4719c9c7c7a9 . Will be closed.
