### ISSUE TITLE
Buffer Length Limit Issue

### ISSUE THREAD

**Issue by felipekm** [Tlantic/cdv-socket-plugin#32]
Today It's not possible to transmit buffer with more than 1024 bytes.

**Comment by vinnylinck** [comment]
Nice catch. Issue planned for release v0.3.1. A elegant solution for future releases.

**Comment by vinnylinck** [comment]
News: a feature to turn the buffer size in a socket configuration is planned on v0.4.0 milestone. Please check issue #33 for further info. Thanks.
