### ISSUE TITLE
Make socket buffer length configurable

### ISSUE THREAD

**Issue by vinnylinck** [Tlantic/cdv-socket-plugin#33]
The buffer size has to be a socket channel configuration, avoiding undesirable data truncation/chopping when receiving data from the server.

The original issue (#32) refers to iOS but it must to be checked in all platforms.

**Comment by felipekm** [comment]
Yeah That's what I'm talking about! :+1:

**Comment by vinnylinck** [comment]
Once the buffer truncation was solved, there is no need to configure such kind of parameter. It will be closed regarding #43 .
