### ISSUE TITLE
single quotes problem

### ISSUE THREAD

**Issue by rheilgm** [Tlantic/cdv-socket-plugin#34]
Hi, i have problem with the function call receivehook; 
I have a server w/c i have no way of editing the response and im stuck with the single quotes problem, here is a sample response and call: 

window.tlantic.plugins.socket.receive('192.168.43.151',8017,'192.168.43.151:8017','{"Type":"status","IsPlaying":true,"IsPaused":false,"IsPlayerOnTop":false,"Title":"Now That You're Gone","CurrentModule":"Music/shares","SelectedItem":"12. Juris Fernandez - Now That You're Gone","WindowId":501}');

**Comment by vinnylinck** [comment]
Hi. Thanks for submitting your question.
Before set this as a bug, I'd like to know what kind of problem are you facing. The socket plugin works with string buffer. So, your application (probably) is trying to perform JSON.parse on the received string, right? Did you notice if the plugin is truncating the information? There is a bug (#32) for that which I'm planning to solve soon.

Other question: what plugin version are you using?

And the last one: I didm't understand how you are receiving the data. I know the docs has a lack of info, but did you try what is specified on the docs (https://github.com/Tlantic/cdv-socket-plugin#receive-host-port-data)?

Last questions:
- you are not trying to implement a socket server with this plugin, right?
- the protocol your server implements is TCP (not UDP), right?
- Is that cordova or phone gap? Which version?
- What are the platforms you are working in your application? iOS? Android? Windows8? The problem happens in all of them?

Sorry for the amount of questions. I just need to map exactly the issue impact to plan a fix as soon as I can.

Thanks a lot for using this plugin.

**Comment by rheilgm** [comment]
Thanks for the reply mate, I really appreciate it.

yes i have no problem with the receiving of data, in fact it really works, but the problem im facing is when single quote is included on server's return because sometimes there are titles that has single quotes included and that would not allow me to listen to the returned data, always returning "Uncaught SyntaxError: Unexpected identifier"

Here's the catch: 
Its a TCP only server, cordova, and  client use only.
im planning to include it on 3 platforms but im still testing it via android, 
In SocketPlugin.java  sendMessage() function we have here:

final String receiveHook = "window.tlantic.plugins.socket.receive('" + host + "'," + port + ",'" + this.buildKey(host, port) + "','" + chunk + "');";

the problem here is the "chunk", correct me if im wrong but this is the data returned by the server right? By the first look, there is no problem but try to return a chunk with single quotes and you will experience the same issue i had.

A simple illustration would be like this:

// imagine this is the receive function
function abc(a){
    console.log(a)
}

abc('My samples'); // valid does return data
abc('My sample's'); // invalid with single quote attached

**Comment by vinnylinck** [comment]
Got that! Need to handle this. I'm submitting an issue (intact, changing the labels) to keep that on track to be solved on the next release (soon, I hope). There are other issues to be fixed as well. 

Please feel free to keep forking / asking / contributing with this plugin.
:+1:

**Comment by rheilgm** [comment]
Thanks, ill keep track on this one and probably will try to test on ios and windows(Haven't tried building them yet)

**Comment by vinnylinck** [comment]
Nice. I'll be waiting for more feedbacks.

**Comment by vinnylinck** [comment]
Reproduced on iOS. working to be fixed on v0.3.1. The intention is to release in a few days. thanks.

**Comment by rheilgm** [comment]
Thanks thats really appreciated! 
Sorry, I was transferred in to anothr project thats why i havent tested this on ios and windows yet. 
Looking forward for the next release :D

**Comment by vinnylinck** [comment]
No problem. We performed some tests and many bugs were fixed for next release.
:)

I hope to publish a new on until next Monday (if not finding other issues)
Thanks.
Vinny
