### ISSUE TITLE
iOS - Connection Pool is not being properly disposed when DisposeConnection

### ISSUE THREAD

**Issue by felipekm** [Tlantic/cdv-socket-plugin#50]
It shouldn't set Null to the pool since there is no connections inside of it?

My suggestion is to test if the Connection Pool count is Zero and if it's true set null to it, cause every time you invoke Connect it's checking if the Pool is null and if it's true it init the pool.

if ([pool count] == 0) {
  pool = nil;
}

Make sense?

**Comment by vinnylinck** [comment]
Buig accepted. Let`s check what is happening. Thx.
