### ISSUE TITLE
iOS - isConnected not turning into true when you do connection recover

### ISSUE THREAD

**Issue by felipekm** [Tlantic/cdv-socket-plugin#51]

**Comment by vinnylinck** [comment]
To be confirmed....

**Comment by vinnylinck** [comment]
This is a huge enhancement. Matter fact, I'm facing this as a bug.
After connection has been classified as stablished, IOS socket has not received stream opened event yet. As a consequence, the "disconnected" flag is not set.

Need to fix this on v0.4.

As a workaround, you ca wrap your send code up in a setTimeout function, giving time to connection handshake process.

I will think on something like that.

Thank you.,

**Comment by felipekm** [comment]
Yup sure, I'm doing that.

**Comment by vinnylinck** [comment]
Nice. Any new?

-----Original Message-----

**Comment by felipekm** [comment]
Nops, I'll let you know when I get something.

**Comment by vinnylinck** [comment]
Nice! Thx

-----Original Message-----
