### ISSUE TITLE
can't receive data util disconnect(android 4.4)

### ISSUE THREAD

**Issue by KillingJacky** [Tlantic/cdv-socket-plugin#56]
connected to some server, server sent some data to android app, but the “SOCKET_RECEIVE_DATA_HOOK” event won't trigger util a disconnection is made by server / cdv-socket-plugin. I use the android v19 sdk. Is this caused by the android API difference between versions?

**Comment by KillingJacky** [comment]
Sorry, I figured out that this issue equals to the "binary support" issue.

**Comment by vinnylinck** [comment]
No problem. :)

**Comment by andrepsc3011** [comment]
I have the same problem. Can someone help me?

**Comment by xAVK** [comment]
I have the same problem. Can someone help me?
