### ISSUE TITLE
Dual license conceivable?

### ISSUE THREAD

**Issue by Gamadril** [Tlantic/cdv-socket-plugin#57]
IMHO your plugin forces all applications that uses it to be licensed under GPL as well. And I'm not sure if they will ever be accepted by Apple on submission. Any chance to make the plugin dual license?

**Comment by vinnylinck** [comment]
No problem. We can open for that. The GPL was the first strategy based on plugin goal. Now, this is growing.... and requiring some review. I'll be glad to change that for next release. I'm planning a new one for next week. If you are blocked, due the licensing subject, we can agree a "mid" release to remove this barrier. Just let me know how things are going and your needs ok? Does that sound like a plan? Thank for your feedback and I hope more feedbacks like these, to have this plugin attending the projects. 
:)

**Comment by Gamadril** [comment]
Thanks, it's not urgent. At the moment I'm just looking for existing socket implementations for cordova. That would be great if I don't have to code my own :) The project I plan to use it for is also open source but under MIT license which is not compatible with GPL. Will wait for the next release.

**Comment by Gamadril** [comment]
any progress on the license issue?

**Comment by felipekm** [comment]
Hi @Gamadril, sorry for the late answer, we're planning this for the next release.
Thanks for your input

**Comment by Gamadril** [comment]
Closing it. I guess this is not going to change. I guess people using it don't even realize that they have GPL violation embedded inside own products.

**Comment by vinnylinck** [comment]
@Gamadril Turns out that everyone of this thread is not working for Tlantic anymore. So, From my side, I can tell we have no access to change a thing on this repo.

I would say it was discontinued. On the other hand, If you see any value, I would be glad to help you on forking this one and create a new maintainable version of this plugin.

Please let me know your thoughts.

Cheers
V.

**Comment by Gamadril** [comment]
@vinnylinck Thanks for the reply. However there is no way to fork GPL code and release it under another license. The whole project should be completely closed as it has actually only some value for some private non-commercial projects which the world will never see in public... It is much easier to write such a plugin from scratch or look for alternatives with suitable license.
