### ISSUE TITLE
Cannot connect to host!

### ISSUE THREAD

**Issue by JoergHolz** [Tlantic/cdv-socket-plugin#58]
I try to establish a connection between an iOS 8 device and an Android 4.4 device and at first I get the message: Established connection with  192.168.178.20:18002 

Few milliseconds later I get «Cannot connect to the host!».

The network is up, no firewall, etc. Is there a way to get a more detailed Error-Message?

**Comment by felipekm** [comment]
How about your server?

**Comment by JoergHolz** [comment]
Maybe I missunderstood something: Is this plugin a server and client solution or just the client and I need a classic websocket-server?

**Comment by vinnylinck** [comment]
This os a tcp socket client plugin... Not a server... No websockets. :)

-----Original Message-----

**Comment by JoergHolz** [comment]
Thx a lot!
