### ISSUE TITLE
Not connecting to the server (usually I use telnet client to connect)

### ISSUE THREAD

**Issue by gamewinner** [Tlantic/cdv-socket-plugin#59]
Hi,

Maybe I'm wrong but I tried to connect to a server with this plugin without success.

Usually on windows I use the Telnet client to connect and send commands to the server.

I tried the client sample but I have connection issues and I can't sent messages.

Am I doing something wrong ?

Thanks a lot,

Kreshnik

PS : 
IP : "192.168.211.130"
Port : 5007

**Comment by felipekm** [comment]
Which platform are you using it for?

**Comment by gamewinner** [comment]
Hi,

I'm using cordova 3.5. Do you think this plugin is the good way to connect to a server like a telnet client ?

Kreshnik

**Comment by felipekm** [comment]
Yes it is, actually I've made my initial testes on this format.
Could you provide more info on this?

Felipe Kautzmann

**Comment by gamewinner** [comment]
I am runing LinuxCNC (http://www.linuxcnc.org/) on Ubuntu.
I can command the software from my Windows 7 using telnet : 

telnet 192.168.211.130 5007

then I send commands like  :

hello EMC x 1.0
set enable EMCTOO
set estop off
...

**Comment by gamewinner** [comment]
I tried to connect to a server in the web and the connection works : checkip.dyndns.org 80

Is this plugin working on local network ? 

What could be the problem ?

Thanks a lot

**Comment by felipekm** [comment]
Check your network permissions and accesses, this should works also on local network.

**Comment by gamewinner** [comment]
I can access to 192.168.211.130:5007 from my computer without problem. My computer is in the same network that my Android phone (Galaxy Note 2).

Do you mean I need to ckeck network permissions and accesses in my Android phone ?

**Comment by felipekm** [comment]
Maybe, try to access some shared folder or similar from your phone.
Your phone should be on this same network.

**Comment by gamewinner** [comment]
Hi,

I found the solution. The problem was the IP of the remote machine (192.168.211.130). I changed it to be in the same sub-network (192.168.1.77) and now it works good.

Thanks for your help.

Kreshnik
